# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trAW_ <- function(rA, rW) {
    .Call('_gRc_trAW_', PACKAGE = 'gRc', rA, rW)
}

trAWB_ <- function(rA, rW, rB) {
    .Call('_gRc_trAWB_', PACKAGE = 'gRc', rA, rW, rB)
}

trAWBW_ <- function(rA, rW, rB) {
    .Call('_gRc_trAWBW_', PACKAGE = 'gRc', rA, rW, rB)
}

trAWBV_ <- function(rA, rW, rB, rV) {
    .Call('_gRc_trAWBV_', PACKAGE = 'gRc', rA, rW, rB, rV)
}

trAWBlist_ <- function(Alist, W, Blist, mode = 0L) {
    .Call('_gRc_trAWBlist_', PACKAGE = 'gRc', Alist, W, Blist, mode)
}

trAWBWlist_ <- function(Alist, W, Blist, mode = 0L) {
    .Call('_gRc_trAWBWlist_', PACKAGE = 'gRc', Alist, W, Blist, mode)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_gRc_RcppExport_registerCCallable', PACKAGE = 'gRc')
})
